# Generated by Django 4.1.4 on 2022-12-20 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ASIOU_PSY_Answer',
            new_name='Answer',
        ),
    ]
