# Generated by Django 4.1.4 on 2022-12-20 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_asiou_psy_answer_answer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='answer',
        ),
    ]
