# Generated by Django 4.1.4 on 2022-12-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_answer_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='anonymus',
            new_name='anonymous',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='available_to_upload',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_table',
        ),
        migrations.RemoveField(
            model_name='question',
            name='manually',
        ),
        migrations.RemoveField(
            model_name='question',
            name='max_ball',
        ),
        migrations.RemoveField(
            model_name='question',
            name='method',
        ),
        migrations.RemoveField(
            model_name='question',
            name='min_ball',
        ),
        migrations.RemoveField(
            model_name='question',
            name='on_graph',
        ),
        migrations.RemoveField(
            model_name='question',
            name='related_question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='required',
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images\\psy_questions\\', verbose_name='Изображение к вопросу'),
        ),
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.CharField(max_length=11, verbose_name='Номер вопроса'),
        ),
        migrations.AlterModelTable(
            name='questiontype',
            table='type_question',
        ),
    ]
