# Generated by Django 4.1.4 on 2022-12-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_anonymus_test_anonymous_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alternative',
            table='form_alternative',
        ),
        migrations.AlterModelTable(
            name='answer',
            table='form_answer',
        ),
        migrations.AlterModelTable(
            name='parttest',
            table='form_part_test',
        ),
        migrations.AlterModelTable(
            name='question',
            table='form_question',
        ),
        migrations.AlterModelTable(
            name='questiontype',
            table='form_type_question',
        ),
        migrations.AlterModelTable(
            name='test',
            table='form_test',
        ),
    ]
