# Generated by Django 4.1.4 on 2022-12-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_alternative_table_alter_answer_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternative',
            name='local_id',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='local_id',
        ),
        migrations.RemoveField(
            model_name='parttest',
            name='local_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='local_id',
        ),
        migrations.RemoveField(
            model_name='test',
            name='local_id',
        ),
    ]
