# Generated by Django 4.1.4 on 2023-02-12 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_alternative_local_id_remove_answer_local_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='part_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.parttest', verbose_name='Часть теста'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(blank=True, default='Новая форма', max_length=100, null=True, verbose_name='Название методики'),
        ),
    ]
