# Generated by Django 4.1.4 on 2023-02-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_question_part_test_alter_test_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='type_question',
        ),
    ]
