# Generated by Django 4.1.4 on 2023-02-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_question_type_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype',
            name='function',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Функция'),
        ),
    ]
