# Generated by Django 4.1.4 on 2023-02-21 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_questiontype_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.questiontype', verbose_name='Тип вопроса'),
        ),
    ]
