# Generated by Django 4.1.4 on 2023-04-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_test_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AddField(
            model_name='test',
            name='trash',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
