# Generated by Django 4.1.4 on 2023-04-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_test_options_test_trash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='variant',
        ),
    ]
