# Generated by Django 4.1.4 on 2023-04-17 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_remove_test_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='alternative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.alternative', verbose_name='Альтернатива'),
        ),
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.IntegerField(verbose_name='Номер вопроса'),
        ),
    ]
